### ISSUE TITLE
python app.py would not run

### ISSUE THREAD

**Issue by manvillej** [patarapolw/anki-export#1]
The if __name__ == '__main__': would only run if the with the directory/file '/Users/patarapolw/PycharmProjects/AnkiTools/tests/input/test.apkg' exists and it wouldn't if someone were to clone the repo. 

This is similarly related to a lack of tests in general. I really like the idea of this project as I use Anki and python a lot, but the lack of tests and docstrings makes me a little concerned about the project health.

**Comment by patarapolw** [comment]
The problem with testing would be how to get a **public** APKG file in the first place, and would it be legal to put APKG in the repo, if APKG is from [Anki Shared Decks](https://ankiweb.net/shared/decks/)?

Otherwise, I shouldn't have problem setting up pytest or even CI (like [pyexcel_xlsxwx](https://github.com/patarapolw/pyexcel-xlsxwx)).

**Comment by patarapolw** [comment]
Should be fixed, and as simple as you hoped now.

See https://github.com/patarapolw/anki-export/tree/master/__extras__/blank-install
